import type { Community, Initiative, Meeting, ScenePlacement, User } from "./domain";

/** Demo sketch on the embankment: 3 trees, 2 benches, 1 bin. */
export const EMBANKMENT_PLACEMENTS: ScenePlacement[] = [
  {
    kind: "tree",
    catalogId: "maf-tree",
    label: "Липа",
    price: 200,
    position: [-6, 0, -4],
    rotation: [0, 0.4, 0],
    scale: [1, 1, 1],
    article: "TR-GRN-01",
    manufacturer: "Питомник «Южный»",
    material: "Саженец липы",
    colorName: "зелёный",
    weightKg: 40,
    lengthM: 1.4,
    widthM: 1.4,
    heightM: 3.2,
  },
  {
    kind: "tree",
    catalogId: "maf-tree",
    label: "Липа",
    price: 200,
    position: [-2, 0, -6],
    rotation: [0, 1.1, 0],
    scale: [1.15, 1.15, 1.15],
    article: "TR-GRN-01",
    manufacturer: "Питомник «Южный»",
    material: "Саженец липы",
    colorName: "зелёный",
    weightKg: 40,
    lengthM: 1.4,
    widthM: 1.4,
    heightM: 3.2,
  },
  {
    kind: "tree",
    catalogId: "maf-tree",
    label: "Липа",
    price: 200,
    position: [3, 0, -5],
    rotation: [0, 0.2, 0],
    scale: [0.9, 0.9, 0.9],
    article: "TR-GRN-01",
    manufacturer: "Питомник «Южный»",
    material: "Саженец липы",
    colorName: "зелёный",
    weightKg: 40,
    lengthM: 1.4,
    widthM: 1.4,
    heightM: 3.2,
  },
  {
    kind: "bench",
    catalogId: "maf-bench",
    label: "Скамейка «Парковая»",
    price: 500,
    position: [-4, 0, 2],
    rotation: [0, 0.6, 0],
    scale: [1, 1, 1],
    article: "TR-MAF-01",
    manufacturer: "Городская среда",
    material: "Лиственница, сталь",
    colorName: "дуб",
    weightKg: 28,
    lengthM: 1.6,
    widthM: 0.58,
    heightM: 0.85,
  },
  {
    kind: "bench",
    catalogId: "maf-bench",
    label: "Скамейка «Парковая»",
    price: 500,
    position: [2, 0, 3],
    rotation: [0, -0.4, 0],
    scale: [1, 1, 1],
    article: "TR-MAF-01",
    manufacturer: "Городская среда",
    material: "Лиственница, сталь",
    colorName: "дуб",
    weightKg: 28,
    lengthM: 1.6,
    widthM: 0.58,
    heightM: 0.85,
  },
  {
    kind: "catalog",
    catalogId: "maf-bin",
    label: "Урна",
    price: 180,
    position: [4.2, 0, 2.2],
    rotation: [0, 0.3, 0],
    scale: [1, 1, 1],
    article: "TR-MAF-02",
    manufacturer: "Городская среда",
    material: "Сталь с порошковой окраской",
    colorName: "графит",
    weightKg: 12,
    lengthM: 0.4,
    widthM: 0.4,
    heightM: 0.7,
  },
];

export { DISTRICTS } from "./districts";

export const USERS: User[] = [
  {
    id: "u-danzin",
    name: "Даниил Зинченко",
    nickname: "danzin",
    role: "citizen",
    districtId: "central",
    points: 186,
    avatarHue: 152,
    achievements: ["first_eye", "ai_innovator"],
    joinedAt: "2026-03-12T10:00:00.000Z",
  },
  {
    id: "u-anna",
    name: "Анна Ковалёва",
    nickname: "anna_tgn",
    role: "citizen",
    districtId: "primorsky",
    points: 94,
    avatarHue: 28,
    achievements: ["first_eye"],
    joinedAt: "2026-04-02T09:00:00.000Z",
  },
  {
    id: "u-igor",
    name: "Игорь Петров",
    nickname: "igor_p",
    role: "citizen",
    districtId: "western",
    points: 241,
    avatarHue: 210,
    achievements: ["first_eye", "builder"],
    joinedAt: "2026-02-18T12:00:00.000Z",
  },
  {
    id: "u-maria",
    name: "Мария Соколова",
    nickname: "masha",
    role: "citizen",
    districtId: "northern",
    points: 67,
    avatarHue: 320,
    achievements: ["first_eye"],
    joinedAt: "2026-05-21T08:00:00.000Z",
  },
  {
    id: "u-elena",
    name: "Елена Васильева",
    nickname: "admin_elena",
    role: "admin_staff",
    districtId: "central",
    points: 0,
    avatarHue: 48,
    achievements: [],
    joinedAt: "2026-01-10T09:00:00.000Z",
  },
  {
    id: "u-sergey",
    name: "Сергей Николаев",
    nickname: "head_sergey",
    role: "admin_head",
    districtId: "central",
    points: 0,
    avatarHue: 265,
    achievements: [],
    joinedAt: "2026-01-10T09:00:00.000Z",
  },
];

function ev(
  at: string,
  status: Initiative["status"],
  comment: string,
  authorId = "u-elena",
  photoAfter = false
): Initiative["history"][number] {
  return { at, status, comment, authorId, photoAfter };
}

export const INITIATIVES: Initiative[] = [
  {
    id: "in-01",
    title: "Ямы на ул. Петровской у дома 84",
    description: "На проезжей части глубокие ямы, машины объезжают по тротуару.",
    reformulated:
      "На ул. Петровской у д. 84 разрушено покрытие проезжей части, пешеходы вынуждены уступать место транспорту.",
    category: "roads",
    categoryConfidence: 0.93,
    priority: "high",
    status: "in_progress",
    lng: 38.9284,
    lat: 47.2159,
    address: "ул. Петровская, д. 84",
    districtId: "central",
    authorId: "u-danzin",
    assignee: "Центральный · Дороги и тротуары",
    photos: ["road"],
    votes: ["u-anna", "u-igor", "u-maria"],
    comments: [
      {
        id: "c-01",
        authorId: "u-anna",
        text: "Подтверждаю, здесь уже полгода так.",
        createdAt: "2026-08-12T11:20:00.000Z",
      },
    ],
    history: [
      ev("2026-08-10T09:12:00.000Z", "new", "Заявка создана", "u-danzin"),
      ev("2026-08-10T10:04:00.000Z", "review", "Принято в работу отдела благоустройства"),
      ev("2026-08-18T14:00:00.000Z", "in_progress", "Подрядчик выехал на замер объёма ямочного ремонта"),
    ],
    createdAt: "2026-08-10T09:12:00.000Z",
    dueAt: "2026-09-09T09:12:00.000Z",
  },
  {
    id: "in-02",
    title: "Не горит фонарь у сквера на Чехова",
    description: "Вечером совсем темно, фонарь мигает и гаснет.",
    reformulated:
      "На ул. Чехова у сквера неисправен светильник уличного освещения, в тёмное время суток участок не освещён.",
    category: "lighting",
    categoryConfidence: 0.96,
    priority: "urgent",
    status: "review",
    lng: 38.924,
    lat: 47.2172,
    address: "ул. Чехова, д. 22",
    districtId: "central",
    authorId: "u-anna",
    assignee: "Центральный · Освещение",
    photos: ["light"],
    votes: ["u-danzin", "u-maria"],
    comments: [],
    history: [
      ev("2026-09-14T19:40:00.000Z", "new", "Заявка создана", "u-anna"),
      ev("2026-09-15T08:10:00.000Z", "review", "Передано службе наружного освещения"),
    ],
    createdAt: "2026-09-14T19:40:00.000Z",
    dueAt: "2026-09-21T19:40:00.000Z",
  },
  {
    id: "in-03",
    title: "Скамейки и деревья на Комсомольской набережной",
    description: "Хочется зону отдыха: скамейки, урны и несколько деревьев у спуска к воде.",
    reformulated:
      "На Комсомольской набережной предлагается устройство зоны отдыха: скамейки, урны и посадка деревьев.",
    category: "green",
    categoryConfidence: 0.88,
    priority: "standard",
    status: "new",
    lng: 38.9388,
    lat: 47.2056,
    address: "наб. Комсомольская, д. 12",
    districtId: "primorsky",
    authorId: "u-danzin",
    assignee: "Приморский · Зелёные насаждения",
    photos: ["embankment"],
    votes: ["u-anna", "u-igor"],
    comments: [
      {
        id: "c-02",
        authorId: "u-igor",
        text: "Отличная идея, летом здесь негде сесть.",
        createdAt: "2026-09-16T16:02:00.000Z",
      },
    ],
    history: [ev("2026-09-16T12:05:00.000Z", "new", "Заявка создана", "u-danzin")],
    visualization: {
      objectCount: 6,
      cost: 1780,
      note: "3 липы, 2 скамейки, 1 урна",
      createdAt: "2026-09-16T12:20:00.000Z",
      lng: 38.9388,
      lat: 47.2056,
      placements: EMBANKMENT_PLACEMENTS,
    },
    createdAt: "2026-09-16T12:05:00.000Z",
    dueAt: "2026-10-07T12:05:00.000Z",
  },
  {
    id: "in-04",
    title: "Детская площадка во дворе на Сызранова",
    description: "Горка сломана, покрытие порвано, детям негде играть.",
    reformulated:
      "Во дворе дома на ул. Сызранова неисправны элементы детской площадки и разрушено покрытие.",
    category: "playground",
    categoryConfidence: 0.91,
    priority: "high",
    status: "in_progress",
    lng: 38.8876,
    lat: 47.2214,
    address: "ул. Сызранова, д. 31",
    districtId: "western",
    authorId: "u-igor",
    assignee: "Западный · Детские площадки",
    photos: ["play"],
    votes: ["u-danzin", "u-anna", "u-maria"],
    comments: [],
    history: [
      ev("2026-07-22T08:00:00.000Z", "new", "Заявка создана", "u-igor"),
      ev("2026-07-23T11:00:00.000Z", "review", "Согласовано с УК"),
      ev("2026-08-04T09:30:00.000Z", "in_progress", "Закуплены элементы МАФ, монтаж на следующей неделе"),
    ],
    createdAt: "2026-07-22T08:00:00.000Z",
    dueAt: "2026-08-12T08:00:00.000Z",
  },
  {
    id: "in-05",
    title: "Переполненные контейнеры на Москатова",
    description: "Мусор не вывозят по графику, вокруг площадки крысы.",
    reformulated:
      "Контейнерная площадка на ул. Москатова переполнена, график вывоза ТКО не соблюдается.",
    category: "waste",
    categoryConfidence: 0.94,
    priority: "urgent",
    status: "done",
    lng: 38.902,
    lat: 47.2286,
    address: "ул. Москатова, д. 9",
    districtId: "western",
    authorId: "u-igor",
    assignee: "Западный · Мусор и уборка",
    photos: ["waste"],
    votes: ["u-maria"],
    comments: [],
    history: [
      ev("2026-08-01T07:40:00.000Z", "new", "Заявка создана", "u-igor"),
      ev("2026-08-01T09:00:00.000Z", "review", "Передано региональному оператору"),
      ev("2026-08-02T13:10:00.000Z", "in_progress", "Дополнительный рейс назначен"),
      ev("2026-08-03T16:00:00.000Z", "done", "Площадка очищена, график скорректирован", "u-elena", true),
    ],
    createdAt: "2026-08-01T07:40:00.000Z",
    dueAt: "2026-08-06T07:40:00.000Z",
  },
  {
    id: "in-06",
    title: "Парковка на газоне у Ленина",
    description: "Каждый вечер машины стоят на газоне, бордюр сбит.",
    reformulated:
      "У ул. Ленина фиксируется стихийная парковка на газоне и повреждение бортового камня.",
    category: "parking",
    categoryConfidence: 0.86,
    priority: "standard",
    status: "review",
    lng: 38.9198,
    lat: 47.2202,
    address: "ул. Ленина, д. 154",
    districtId: "central",
    authorId: "u-maria",
    assignee: "Центральный · Парковка",
    photos: ["parking"],
    votes: ["u-danzin"],
    comments: [],
    history: [
      ev("2026-09-08T18:22:00.000Z", "new", "Заявка создана", "u-maria"),
      ev("2026-09-09T09:15:00.000Z", "review", "Направлен запрос в ГИБДД и УК"),
    ],
    createdAt: "2026-09-08T18:22:00.000Z",
    dueAt: "2026-09-22T18:22:00.000Z",
  },
  {
    id: "in-07",
    title: "Просадка люка на Греческой",
    description: "Люк просел, можно попасть ногой. Рядом школа.",
    reformulated:
      "На ул. Греческой просел колодезный люк вблизи школы — риск травмы пешеходов.",
    category: "housing",
    categoryConfidence: 0.9,
    priority: "urgent",
    status: "in_progress",
    lng: 38.9335,
    lat: 47.2128,
    address: "ул. Греческая, д. 47",
    districtId: "central",
    authorId: "u-anna",
    assignee: "Центральный · ЖКХ и коммуникации",
    photos: ["hatch"],
    votes: ["u-danzin", "u-igor", "u-maria"],
    comments: [],
    history: [
      ev("2026-09-11T07:05:00.000Z", "new", "Заявка создана", "u-anna"),
      ev("2026-09-11T07:40:00.000Z", "review", "Приоритет повышен: рядом школа"),
      ev("2026-09-12T10:00:00.000Z", "in_progress", "Водоканал выехал на объект"),
    ],
    createdAt: "2026-09-11T07:05:00.000Z",
    dueAt: "2026-09-25T07:05:00.000Z",
  },
  {
    id: "in-08",
    title: "Нет освещения во дворе на Щаденко",
    description: "Двор Северного района вечером полностью тёмный.",
    reformulated:
      "Во дворе дома на ул. Щаденко отсутствует рабочее дворовое освещение.",
    category: "lighting",
    categoryConfidence: 0.92,
    priority: "high",
    status: "new",
    lng: 38.8942,
    lat: 47.2412,
    address: "ул. Щаденко, д. 18",
    districtId: "northern",
    authorId: "u-maria",
    assignee: "Северный · Освещение",
    photos: ["yard-dark"],
    votes: [],
    comments: [],
    history: [ev("2026-09-18T20:11:00.000Z", "new", "Заявка создана", "u-maria")],
    createdAt: "2026-09-18T20:11:00.000Z",
    dueAt: "2026-09-25T20:11:00.000Z",
  },
  {
    id: "in-09",
    title: "Клумбы у дома на Солнечной",
    description: "Хотим клумбы вместо вытоптанного газона.",
    reformulated:
      "Во дворе дома на ул. Солнечной предлагается устройство клумб на месте вытоптанного газона.",
    category: "green",
    categoryConfidence: 0.84,
    priority: "standard",
    status: "review",
    lng: 38.9425,
    lat: 47.2608,
    address: "ул. Солнечная, д. 9",
    districtId: "solar",
    authorId: "u-danzin",
    assignee: "Солнечный · Зелёные насаждения",
    photos: ["lawn"],
    votes: ["u-anna"],
    comments: [],
    history: [
      ev("2026-09-05T13:00:00.000Z", "new", "Заявка создана", "u-danzin"),
      ev("2026-09-06T10:20:00.000Z", "review", "Направлено в отдел озеленения"),
    ],
    createdAt: "2026-09-05T13:00:00.000Z",
    dueAt: "2026-09-26T13:00:00.000Z",
  },
  {
    id: "in-10",
    title: "Сломанная урна у остановки на Дзержинского",
    description: "Урна перевёрнута, мусор разносится ветром.",
    reformulated:
      "У остановки на ул. Дзержинского повреждена урна, территория загрязняется.",
    category: "waste",
    categoryConfidence: 0.89,
    priority: "standard",
    status: "done",
    lng: 38.941,
    lat: 47.2088,
    address: "ул. Дзержинского, д. 155",
    districtId: "primorsky",
    authorId: "u-anna",
    assignee: "Приморский · Мусор и уборка",
    photos: ["bin"],
    votes: ["u-danzin"],
    comments: [],
    history: [
      ev("2026-07-02T09:00:00.000Z", "new", "Заявка создана", "u-anna"),
      ev("2026-07-02T12:00:00.000Z", "review", "Принято"),
      ev("2026-07-04T11:00:00.000Z", "in_progress", "Замена урны"),
      ev("2026-07-05T15:30:00.000Z", "done", "Установлена новая урна", "u-elena", true),
    ],
    createdAt: "2026-07-02T09:00:00.000Z",
    dueAt: "2026-07-07T09:00:00.000Z",
  },
  {
    id: "in-11",
    title: "Тротуар к школе № 8 разбит",
    description: "Дети идут по проезжей части.",
    reformulated:
      "Тротуар к школе № 8 разрушен, школьники вынуждены идти по проезжей части.",
    category: "roads",
    categoryConfidence: 0.9,
    priority: "high",
    status: "rejected",
    lng: 38.9154,
    lat: 47.2189,
    address: "ул. Фрунзе, д. 60",
    districtId: "central",
    authorId: "u-igor",
    assignee: "Центральный · Дороги и тротуары",
    photos: ["sidewalk"],
    votes: ["u-danzin", "u-anna"],
    comments: [
      {
        id: "c-03",
        authorId: "u-elena",
        text: "Участок включён в план ремонта 2027 года. Отклонено как отдельная заявка.",
        createdAt: "2026-06-20T10:00:00.000Z",
      },
    ],
    history: [
      ev("2026-06-11T08:30:00.000Z", "new", "Заявка создана", "u-igor"),
      ev("2026-06-12T09:00:00.000Z", "review", "Рассмотрено"),
      ev(
        "2026-06-20T10:00:00.000Z",
        "rejected",
        "Участок включён в адресную программу 2027 года"
      ),
    ],
    createdAt: "2026-06-11T08:30:00.000Z",
    dueAt: "2026-07-11T08:30:00.000Z",
  },
  {
    id: "in-12",
    title: "Качели во дворе Михайловки",
    description: "Просим поставить качели и одну скамейку для родителей.",
    reformulated:
      "Во дворе дома в Михайловке предлагается установка качелей и скамейки для родителей.",
    category: "playground",
    categoryConfidence: 0.87,
    priority: "standard",
    status: "new",
    lng: 38.9444,
    lat: 47.2678,
    address: "ул. Михайловская, д. 18",
    districtId: "mikhailovka",
    authorId: "u-maria",
    assignee: "Михайловка · Детские площадки",
    photos: ["swing"],
    votes: ["u-igor"],
    comments: [],
    history: [ev("2026-09-17T15:44:00.000Z", "new", "Заявка создана", "u-maria")],
    createdAt: "2026-09-17T15:44:00.000Z",
    dueAt: "2026-10-08T15:44:00.000Z",
  },
];

export const COMMUNITIES: Community[] = [
  {
    id: "cm-1",
    type: "street",
    name: "ул. Петровская",
    members: 128,
    description: "Жители центральной улицы: тротуары, фасады, освещение.",
    districtId: "central",
  },
  {
    id: "cm-2",
    type: "district",
    name: "Приморский район",
    members: 340,
    description: "Набережная, пляж, летние зоны отдыха.",
    districtId: "primorsky",
  },
  {
    id: "cm-3",
    type: "thematic",
    name: "Чистый двор",
    members: 86,
    description: "Вывоз ТКО, контейнерные площадки, субботники.",
  },
  {
    id: "cm-4",
    type: "thematic",
    name: "Зелёный город",
    members: 64,
    description: "Посадки, клумбы, полив и сохранение деревьев.",
  },
  {
    id: "cm-5",
    type: "street",
    name: "Двор Сызранова, 31",
    members: 41,
    description: "Площадка, парковка и освещение одного двора.",
    districtId: "western",
  },
];

export const MEETINGS: Meeting[] = [
  {
    id: "mt-1",
    title: "Набережная: зона отдыха",
    type: "workgroup",
    initiativeId: "in-03",
    when: "2026-09-24T17:00:00.000Z",
    agenda: "Обсудить расстановку скамеек и деревьев на Комсомольской набережной.",
    participants: 12,
    maxParticipants: 50,
    hostId: "u-danzin",
  },
  {
    id: "mt-2",
    title: "Час вопросов с администрацией",
    type: "district",
    when: "2026-09-26T16:00:00.000Z",
    agenda: "Отчёт по срокам ремонта дорог Центрального района.",
    participants: 28,
    maxParticipants: 50,
    hostId: "u-sergey",
  },
  {
    id: "mt-3",
    title: "Дворовый чат Сызранова",
    type: "yard",
    initiativeId: "in-04",
    when: "2026-09-22T18:30:00.000Z",
    agenda: "Согласовать комплект МАФ для детской площадки.",
    participants: 9,
    maxParticipants: 30,
    hostId: "u-igor",
  },
];

export const DEMO_USER_ID = "u-danzin";
